// CHG-014 D: v6 通用原语 — 纯 chrome，portal 装配方按需引用。
export { default as FileRefChip } from './FileRefChip.vue'
export { default as SegControl } from './SegControl.vue'
export type { SegOption } from './SegControl.vue'
export { default as KpiRow } from './KpiRow.vue'
export type { KpiItem } from './KpiRow.vue'
export { default as HeatBar } from './HeatBar.vue'
export { default as StatusDot } from './StatusDot.vue'
export { default as CliIcon } from './CliIcon.vue'
export { default as EnvChip } from './EnvChip.vue'
export { default as MselPop } from './MselPop.vue'
export type { MselItem, MselColumn } from './MselPop.vue'
export { default as ComposerShell } from './ComposerShell.vue'
export { default as DockBar } from './DockBar.vue'
export type { DockTab } from './DockBar.vue'
export { default as RoundNav } from './RoundNav.vue'
